name: docker-build
run-name: Docker build

on:
  workflow_call:
    inputs:
      images:
        description: 'Image name. Example: `ghcr.io/giyomoon/workflows`'
        type: string
        required: true

      platforms:
        description: 'Platforms to build for. Default: `linux/amd64`'
        type: string
        required: false
        default: linux/amd64

      workdir:
        description: 'Directory of the Dockerfile to build. Default is the root of the repository. Useful for monorepos'
        type: string
        required: false
        default: '.'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.workdir }}/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.images }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: "{{defaultContext}}:${{ inputs.workdir }}"
          push: true
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
