name: docker-build
run-name: Docker build

on:
  workflow_call:
    inputs:
      images:
        description: 'Image name. Example: `ghcr.io/giyomoon/workflows`'
        type: string
        required: true
      platforms:
        description: 'Platforms to build for. Default: `linux/amd64,linux/arm64`'
        type: string
        required: false
        default: linux/amd64,linux/arm64
      workdir:
        description: 'Directory of the Dockerfile to build. Default is the root of the repository. Useful for monorepos'
        type: string
        required: false
        default: ''

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Lint Dockerfile with ignore
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.workdir }}/Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: |
            type=semver,pattern={{version}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}${{ inputs.workdir && ':' }}${{ inputs.workdir }}"
          push: true
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ inputs.images }}:buildcache
          cache-to: type=registry,ref=${{ inputs.images }}:buildcache,mode=max
