name: js-lint
run-name: Javascript Lint

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Nodejs version to use. Default is `lts`'
        type: string
        required: false
        default: 'lts'
      workdir:
        description: 'Directory of the javascript code to lint. Default is the root of the repository. Useful for monorepos'
        type: string
        required: false
        default: '.'

jobs:
  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.rust-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Get pnpm store dir
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: |
          cd ${{ inputs.workdir }}
          pnpm install
      - name: Lint
        run: |
          cd ${{ inputs.workdir }}
          pnpm lint
