name: rust-audit
run-name: Rust audit

on:
  workflow_call:
    inputs:
      rust-version:
        description: 'Rust toolchain version to use. Default is `beta`'
        type: string
        required: false
        default: 'beta'
      workdir:
        description: 'Directory of the Rust project to check. Default is the root of the repository. Useful for monorepos'
        type: string
        required: false
        default: '.'

jobs:
  rust-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain ${{ inputs.rust-version }} --profile minimal -c rustfmt,clippy -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install tools
        run: |
          cargo install cargo-audit
      - name: Audit
        run: |
          cd ${{ inputs.workdir }}
          rm -rf ~/.cargo/advisory-db
          cargo audit
