name: rust-install
run-name: Rust install

on:
  workflow_call:
    inputs:
      rust-version:
        description: 'Rust toolchain version to use. Default is `beta`'
        type: string
        required: false
        default: beta
    components:
        description: 'Additional toolchain components to install. For example `rustfmt,clippy`'
        required: false
        type: string

jobs:
  rust-install:
    runs-on: ubuntu-latest
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs --output install.sh
      - run: chmod 755 ./install.sh
      - run: ./install.sh --default-toolchain ${{ inputs.toolchain }} --profile minimal ${{ inputs.components && '-c' }} ${{ inputs.components }} -y
